dist: trusty
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: node_js
node_js:
  - 4
  - 6
env:
  - TESTSUITE=test

script:
  - if [[ "$TESTSUITE" == "lint" ]]; then npm run lint; fi
  - if [[ "$TESTSUITE" == "test" ]]; then npm test; fi
  - if [[ "$TESTSUITE" == "cover" ]]; then npm run cover; fi

after_success:
  - if [[ "$TESTSUITE" == "cover" ]]; then npm run report-to-coveralls; fi

jobs:
  include:
    - node_js: 8
      env: TESTSUITE=cover
    - node_js: 8
      env: TESTSUITE=lint
    - stage: deploy
      node_js: 8
      script: skip
      deploy:
        - provider: script
          script: npm run git-publish
          skip_cleanup: true
          on:
            branch: master
            repo: slowli/exonum-types
